#!/usr/bin/perl -w
  use strict;
  my $debug=1;
  my @staff;
  my @work_hour = (7.5, 7.5, 7.5, 8, 6.5, 9, 9, 9);
  print "===== Debug Mode =====\n", if($debug); 
  ### Staff {{{
  open FP, "staff.csv";
  while(<FP>) {
    chomp($_);
    push @staff, $_;
  }
  close FP;
  print " >>> Staff list:@staff\n", if($debug);
  #}}}
  ### Day off {{{
  open FP, "day_off.csv";

  close FP;
  # }}}
  ### Calendar {{{
  my $nu_week = `echo -n "\$((\`cal -h| wc -l\`-2))"`;
  my @cal_weeks = `cal -h | tail -n $nu_week | head -n \$(($nu_week-1))`;
  my $first_sunday = $1, if($cal_weeks[0]=~/(\d)\s*$/);
  my $last_day = $1, if($cal_weeks[$#cal_weeks]=~/(\d+)\s*$/);
  #my $first_weekdays = $cal_weeks[0];
  print " >>> First sunday of month: $first_sunday\n", if($debug);
  print " >>> The last day of month: $last_day\n", if($debug);
  #print " >>> First weekdays: $first_weekdays\n", if($debug);
  # }}}

  print "======================\n", if($debug); 
